services:                           # Раздел для описания запускаемых программ (сервисов)
  postgres:                         # Имя сервиса (базы данных)
    image: postgres:17              # Готовый шаблон: берем официальный PostgreSQL версии 17
    container_name: marketcore-postgres  # Понятное имя контейнера в списке Docker
    restart: unless-stopped         # Авто-перезапуск при сбоях или перезагрузке ПК
    environment:                    # Настройки (переменные), передаваемые внутрь контейнера
      POSTGRES_USER: marketcore     # Логин администратора базы данных
      POSTGRES_PASSWORD: marketcore # Пароль администратора базы данных
      POSTGRES_DB: marketcore       # Имя создаваемой по умолчанию базы данных
    ports:                          # Настройка доступа к базе снаружи
      - "5432:5432"                 # Проброс: ПК (5432) -> Контейнер (5432)
    volumes:                        # Подключение внешнего диска для сохранения данных
      - postgres_data:/var/lib/postgresql/data # Папка на ПК -> Папка с файлами БД в контейнере

volumes:                            # Раздел объявления внешних дисков (томов)
  postgres_data:                    # Регистрация диска postgres_data, чтобы данные не стерлись